# Generated by Django 5.2.10 on 2026-02-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'managed': False},
        ),
    ]
