# Generated by Django 5.2.10 on 2026-02-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_alter_conference_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conference',
            table='CONFERENCE',
        ),
    ]
