# Generated by Django 5.2.10 on 2026-02-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('MaNguoiDung', models.AutoField(primary_key=True, serialize=False)),
                ('HoTen', models.CharField(max_length=100)),
                ('TaiKhoan', models.CharField(max_length=50, unique=True)),
                ('MatKhau', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('VaiTro', models.CharField(default='Member', max_length=20)),
            ],
            options={
                'db_table': 'USER',
            },
        ),
    ]
