# Generated by Django 6.0.1 on 2026-02-05 17:50

import apps.submissions.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('camera_ready', 'Camera Ready')], default='submitted', max_length=20)),
                ('paper_id', models.CharField(default=apps.submissions.models.generate_unique_paper_id, editable=False, max_length=4, unique=True)),
                ('camera_ready_deadline', models.DateTimeField(blank=True, null=True)),
                ('camera_ready_file', models.FileField(blank=True, null=True, upload_to='camera_ready/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
